package com;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.xml.bind.annotation.XmlRootElement
public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;


	@org.kie.api.definition.type.Label("Patient ID")
	public java.lang.String patientID;

	@org.kie.api.definition.type.Label(value = "Patient Name")
	public  java.lang.String patientName;

	@org.kie.api.definition.type.Label("Patient Gender")
	public java.lang.String patientGender;
	
	@org.kie.api.definition.type.Label("Patient DOB")
	public  java.lang.String patientDOB;

	@org.kie.api.definition.type.Label("Conditions")
	public java.util.List<CodedElement> conditions = new ArrayList<CodedElement>();
	
	@org.kie.api.definition.type.Label("Comorbidity Status")
	public java.lang.String comorbidityStatus = "ABSENT";
	
	@org.kie.api.definition.type.Label("Microvascular Complications")
	public java.lang.String microvascularComplications  = "ABSENT";

	@org.kie.api.definition.type.Label(value = "Medications")
	public java.util.List<CodedElement> medications = new ArrayList<CodedElement>();;
	
	@org.kie.api.definition.type.Label("Blood Sugar")
	public Integer bloodSugar;
	
	@org.kie.api.definition.type.Label("HBA1C Range High")
	public double hbA1cRangeHigh;

	@org.kie.api.definition.type.Label("HBA1C Range Low")
	public double hbA1cRangeLow;

	@org.kie.api.definition.type.Label("HBA1C Status")
	public java.lang.String hba1cStatus;

	@org.kie.api.definition.type.Label("Latest HBA1C")
	public double latestHBA1C;

	@org.kie.api.definition.type.Label("Severity")
	public java.lang.Boolean severeStatus;
	
	public Patient() {
		this.severeStatus = false;
	}

	public Patient(String patientID, Integer bloodSugar, double hbA1cRangeLow, double hbA1cRangeHigh,
			String patientGender, Boolean severeStatus, List<CodedElement> conditions, String comorbidityStatus,
			String microvascularComplications, double latestHBA1C, String hba1cStatus, String patientDOB,
			String patientName, java.util.List<CodedElement> medications) {
		super();
		this.patientID = patientID;
		this.bloodSugar = bloodSugar;
		this.hbA1cRangeLow = hbA1cRangeLow;
		this.hbA1cRangeHigh = hbA1cRangeHigh;
		this.patientGender = patientGender;
		this.severeStatus = severeStatus;
		this.conditions = conditions;
		this.comorbidityStatus = comorbidityStatus;
		this.microvascularComplications = microvascularComplications;
		this.latestHBA1C = latestHBA1C;
		this.hba1cStatus = hba1cStatus;
		this.patientDOB = patientDOB;
		this.patientName = patientName;
		this.medications = medications;
	}

	public java.lang.Integer getBloodSugar() {
		return this.bloodSugar;
	}

	public java.util.List<CodedElement> getConditions() {
		return this.conditions;
	}

	public java.lang.String getComorbidityStatus() {
		return this.comorbidityStatus;
	}

	public double getHbA1cRangeHigh() {
		return this.hbA1cRangeHigh;
	}

	public double getHbA1cRangeLow() {
		return this.hbA1cRangeLow;
	}

	public java.lang.String getHba1cStatus() {
		return this.hba1cStatus;
	}

	public double getLatestHBA1C() {
		return this.latestHBA1C;
	}

	public java.util.List<CodedElement> getMedications() {
		return medications;
	}

	public java.lang.String getMicrovascularComplications() {
		return this.microvascularComplications;
	}

	public java.lang.String getPatientDOB() {
		return this.patientDOB;
	}

	public java.lang.String getPatientGender() {
		return this.patientGender;
	}

	public java.lang.String getPatientID() {
		return this.patientID;
	}

	public java.lang.String getPatientName() {
		return this.patientName;
	}

	public java.lang.Boolean getSevereStatus() {
		return this.severeStatus;
	}

	public void setBloodSugar(java.lang.Integer bloodSugar) {
		this.bloodSugar = bloodSugar;
	}

	public void setConditions(java.util.List<CodedElement> conditions) {
		if (conditions != null) {
			this.conditions.addAll(conditions);
		}
	}

	public void setComorbidityStatus(java.lang.String comorbidityStatus) {
		this.comorbidityStatus = comorbidityStatus;
	}

	public void setHbA1cRangeHigh(double hbA1cRangeHigh) {
		this.hbA1cRangeHigh = hbA1cRangeHigh;
	}

	public void setHbA1cRangeLow(double hbA1cRangeLow) {
		this.hbA1cRangeLow = hbA1cRangeLow;
	}

	public void setHba1cStatus(java.lang.String hba1cStatus) {
		this.hba1cStatus = hba1cStatus;
	}

	public void setLatestHBA1C(double latestHBA1C) {
		this.latestHBA1C = latestHBA1C;
	}

	public void setMedications(java.util.List<CodedElement> medications) {
		if (medications != null) {
			this.medications.addAll(medications);
		}
	}

	public void setMicrovascularComplications(
			java.lang.String microvascularComplications) {
		this.microvascularComplications = microvascularComplications;
	}

	public void setPatientDOB(java.lang.String patientDOB) {
		this.patientDOB = patientDOB;
	}

	public void setPatientGender(java.lang.String patientGender) {
		this.patientGender = patientGender;
	}

	public void setPatientID(java.lang.String patientID) {
		this.patientID = patientID;
	}

	public void setPatientName(java.lang.String patientName) {
		this.patientName = patientName;
	}

	public void setSevereStatus(java.lang.Boolean severeStatus) {
		this.severeStatus = severeStatus;
	}

 
}